[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/problem_stats"
  to = "/.netlify/functions/solved-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/rating_warning_problems"
  to = "/.netlify/functions/solved-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/unsolved_rating_warning_problems"
  to = "/.netlify/functions/solved-proxy"
  status = 200
  force = true